# Generated by Django 4.2.9 on 2024-02-26 16:55

from django.db import migrations, models
import kinomania.movies.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rows', models.PositiveIntegerField()),
                ('seats_per_row', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/', validators=[kinomania.movies.validators.validate_file_size])),
                ('slug', models.CharField(unique=True)),
            ],
        ),
    ]
