# Generated by Django 4.2.9 on 2024-02-04 15:33

from django.db import migrations, models
import kinomania.movies.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('year', models.PositiveIntegerField(validators=[kinomania.movies.validators.validate_year])),
                ('genres', models.CharField(default='Action | Comedy | Romance | Horror | Thriller', max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', validators=[kinomania.movies.validators.validate_file_size])),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('duration', models.CharField(max_length=20)),
                ('trailer', models.CharField(default='null', max_length=300)),
                ('rdate', models.CharField(default='null', max_length=20)),
                ('imdb_link', models.URLField(verbose_name='Link to IMDB')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
